### ISSUE TITLE
Setting up a Kanban Project - My Catalog

### ISSUE THREAD

**Issue by niicode** [samiullah997/catalog-of-things#26]
**Kanban board review | Catalog of my Things**
In this issue we have :
[Link to project board](https://github.com/samiullah997/catalog-of-things/projects/1)

- Assigned tasks to each other for each card, and for group tasks as well.
- We are a group of 3 Micronauts as assigned below
  - Member 1: @samiullah997 
  - Member 2: @niicode 
  - Member 3: @t-bello7 
- We have marked the Member 4 tasks as optional as well

**Comment by samiullah997** [comment]
**Kanban board review | Catalog of my Things**
In this issue we have :

- Assigned tasks to each other for each card, and for group tasks as well.
- We are a group of 3 Micronauts as assigned below
  - Member 1: @samiullah997 
  - Member 2: @niicode 
  - Member 3: @t-bello7 
- We have marked the Member 4 tasks as optional as well

**Comment by prolajumokeoni** [comment]
Hi @Team
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good issuedescription



## Required Changes ♻️

- [ ] Kindly make sure that you create cards on the project board following [project requirements divided for each team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) and compare it with the [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md).


- [ ] Each task should be a separate card that: 
- Has a description of the task.

- [ ] Based on the requirements, Each of the team members should assign themselves to the cards as divided in the [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by brytebee** [comment]
Hi, Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
